name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push the snake graph
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add github-contribution-grid-snake.svg
          git commit -m "Generated contribution snake" || echo "No changes to commit"
          git push
