name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: snake-artifact
          path: github-contribution-grid-snake.svg
